import type { Recipe } from '@/types';

export const recipes: Recipe[] = [
  {
    id: '1',
    slug: 'classic-croissant',
    title: 'Classic Croissant',
    description: 'Buttery, flaky layers made with a traditional laminated dough — the cornerstone of French pastry.',
    category: 'pastry',
    tone: 'caramel',
    ratio: 'portrait',
    time: '3 days',
    difficulty: 'Advanced',
    featured: true,
  },
  {
    id: '2',
    slug: 'pain-au-chocolat',
    title: 'Pain au Chocolat',
    description: 'Dark chocolate nestled inside crisp, golden croissant dough. A Parisian staple done right.',
    category: 'pastry',
    tone: 'cocoa',
    ratio: 'portrait',
    time: '3 days',
    difficulty: 'Advanced',
    featured: true,
  },
  {
    id: '3',
    slug: 'sourdough-boule',
    title: 'Sourdough Boule',
    description: 'A chewy, open-crumb loaf with a blistered crust — fermented low and slow for full flavor.',
    category: 'bread',
    tone: 'mocha',
    ratio: 'square',
    time: '24 hrs',
    difficulty: 'Intermediate',
    featured: true,
  },
  {
    id: '4',
    slug: 'lemon-tart',
    title: 'Lemon Tart',
    description: 'Silky lemon curd in a crisp, buttery shell with a torched meringue crown.',
    category: 'pastry',
    tone: 'cream',
    ratio: 'landscape',
    time: '2 hrs',
    difficulty: 'Intermediate',
    featured: false,
  },
  {
    id: '5',
    slug: 'financiers',
    title: 'Brown Butter Financiers',
    description: 'Mini almond cakes with a golden crust, tender crumb, and deep nutty flavour.',
    category: 'cake',
    tone: 'peach',
    ratio: 'landscape',
    time: '45 min',
    difficulty: 'Easy',
    featured: false,
  },
  {
    id: '6',
    slug: 'kouign-amann',
    title: 'Kouign-Amann',
    description: 'The Breton caramelised pastry — layers of buttery dough folded with sugar and baked until crisp.',
    category: 'pastry',
    tone: 'caramel',
    ratio: 'square',
    time: '4 hrs',
    difficulty: 'Intermediate',
    featured: false,
  },
  {
    id: '7',
    slug: 'chocolate-fondant',
    title: 'Chocolate Fondant',
    description: 'A molten-centred chocolate cake that sets up in minutes and impresses every time.',
    category: 'cake',
    tone: 'cocoa',
    ratio: 'portrait',
    time: '30 min',
    difficulty: 'Easy',
    featured: false,
  },
  {
    id: '8',
    slug: 'earl-grey-shortbread',
    title: 'Earl Grey Shortbread',
    description: 'Crisp, melt-in-your-mouth shortbread infused with bergamot and black tea.',
    category: 'cookies',
    tone: 'cream',
    ratio: 'landscape',
    time: '1 hr',
    difficulty: 'Easy',
    featured: false,
  },
];

export type StatItem = {
  value: number;
  suffix?: string;
  label: string;
};

export const stats: StatItem[] = [
  { value: 14, suffix: 'k+', label: 'Newsletter subscribers' },
  { value: 2, suffix: ' yrs', label: 'Pastry school trained' },
  { value: 120, suffix: '+', label: 'Published recipes' },
  { value: 8, suffix: '', label: 'Brand partnerships' },
];
