import type { Recipe, Stat } from '@/types';

export const recipes: Recipe[] = [
  {
    slug: 'classic-croissant',
    title: 'Classic Croissant',
    description: 'The perfect laminated dough croissant with 27 layers of buttery goodness.',
    category: 'pastry',
    tone: 'caramel',
    time: '3 hours',
    difficulty: 'Advanced',
    featured: true,
  },
  {
    slug: 'pain-au-chocolat',
    title: 'Pain au Chocolat',
    description: 'Flaky pastry wrapped around rich dark chocolate. A French bakery staple.',
    category: 'pastry',
    tone: 'mocha',
    time: '3 hours',
    difficulty: 'Advanced',
    featured: true,
  },
  {
    slug: 'sourdough-boule',
    title: 'Sourdough Boule',
    description: 'A rustic round loaf with a crisp crust and open, chewy crumb.',
    category: 'bread',
    tone: 'peach',
    time: '24 hours',
    difficulty: 'Intermediate',
    featured: true,
  },
  {
    slug: 'lemon-tart',
    title: 'Classic Lemon Tart',
    description: 'Silky lemon curd in a buttery pâte sucrée shell. Elegant simplicity.',
    category: 'tart',
    tone: 'cream',
    time: '2 hours',
    difficulty: 'Intermediate',
  },
  {
    slug: 'choux-eclairs',
    title: 'Chocolate Éclairs',
    description: 'Crisp choux pastry filled with pastry cream and topped with dark chocolate glaze.',
    category: 'pastry',
    tone: 'cocoa',
    time: '2.5 hours',
    difficulty: 'Advanced',
  },
  {
    slug: 'almond-financiers',
    title: 'Almond Financiers',
    description: 'Nuttybrown-butter cakes with a moist crumb and golden crust.',
    category: 'cake',
    tone: 'caramel',
    time: '45 min',
    difficulty: 'Beginner',
  },
  {
    slug: 'mille-feuille',
    title: 'Mille-Feuille',
    description: 'A thousand layers of caramelised puff pastry with vanilla diplomat cream.',
    category: 'pastry',
    tone: 'cream',
    time: '4 hours',
    difficulty: 'Advanced',
  },
  {
    slug: 'brioche-loaf',
    title: 'Brioche Loaf',
    description: 'Rich, pillowy enriched bread with a tender crumb and deep golden crust.',
    category: 'bread',
    tone: 'peach',
    time: '4 hours',
    difficulty: 'Intermediate',
  },
  {
    slug: 'raspberry-tart',
    title: 'Raspberry & Rose Tart',
    description: 'Floral crème pâtissière topped with fresh raspberries in a sweet pastry shell.',
    category: 'tart',
    tone: 'rose',
    time: '2.5 hours',
    difficulty: 'Intermediate',
  },
  {
    slug: 'pistachio-cake',
    title: 'Pistachio Layer Cake',
    description: 'Three layers of moist pistachio sponge with whipped pistachio buttercream.',
    category: 'cake',
    tone: 'pistachio',
    time: '3 hours',
    difficulty: 'Intermediate',
  },
  {
    slug: 'kouign-amann',
    title: 'Kouign-Amann',
    description: 'A Breton specialty of caramelised, laminated yeasted dough. Crisp and sticky.',
    category: 'pastry',
    tone: 'caramel',
    time: '3.5 hours',
    difficulty: 'Advanced',
  },
  {
    slug: 'madeleines',
    title: 'Classic Madeleines',
    description: 'Shell-shaped French sponge cakes with a distinctive hump and lemon zest.',
    category: 'cake',
    tone: 'cream',
    time: '1 hour',
    difficulty: 'Beginner',
  },
];

export const stats: Stat[] = [
  { value: 14, suffix: 'k+', label: 'Newsletter subscribers' },
  { value: 3, suffix: '+', label: 'Years in pastry school' },
  { value: 120, suffix: '+', label: 'Recipes published' },
  { value: 40, suffix: 'k+', label: 'Monthly readers' },
];
