import type { RecipeDetail } from '@/types';

// Local image imports — these are the real uploaded photos placed in /public/images/
// We reference them via absolute paths from /public
export const RECIPE_IMAGES = {
  almondCroissant:     '/images/almond-croissant.jpg',
  strawberryShortcake: '/images/strawberry-shortcake.jpg',
  macarons:            '/images/macarons.jpg',
  pumpkinCookie:       '/images/pumpkin-cookie.jpg',
  lemonCurd:           '/images/lemon-curd.jpg',
  allisonPortrait:     '/images/allison-portrait.jpg',
  polaroid1:           '/images/polaroid-1.jpg',
  polaroid2:           '/images/polaroid-2.jpg',
  polaroid3:           '/images/polaroid-3.jpg',
  polaroid4:           '/images/polaroid-4.jpg',
};

export const recipeDetails: RecipeDetail[] = [
  {
    slug: 'almond-croissant',
    title: 'The Ultimate Easy Almond Croissant Recipe',
    category: 'Pastries',
    image: RECIPE_IMAGES.almondCroissant,
    prepTime: '20 min',
    cookTime: '20–25 min',
    yield: 'Makes 4 croissants',
    intro: `Back when I was staging at Breads Bakery in New York — which is inspired by the legendary Lehamim Bakery in Tel Aviv — I fell completely in love with their almond croissants. They'd take day-old croissants, soak them in simple syrup, stuff and coat them with almond cream (frangipane), then shower them in sliced almonds and powdered sugar. The result? Crispy, custardy, nutty, and deeply satisfying. The best part: you don't need to make croissant dough from scratch. This is a "leftover croissant" recipe — and it might be one of the best things you ever make.`,
    sections: [
      {
        heading: 'Simple Syrup',
        ingredients: [
          '100g water',
          '100g sugar',
          '1 tsp vanilla extract (optional)',
          '1 tbsp rum or amaretto (optional)',
        ],
        steps: [
          'Combine water and sugar in a small saucepan over medium heat.',
          'Stir until sugar is fully dissolved. Remove from heat.',
          'Add vanilla and/or rum if using. Let cool completely.',
        ],
      },
      {
        heading: 'Almond Cream (Frangipane)',
        ingredients: [
          '115g (1 stick) unsalted butter, room temperature',
          '115g (1 cup) almond flour',
          '115g (1 cup) powdered sugar, sifted',
          '2 large eggs, room temperature',
          '1 tsp vanilla extract',
          '1 tbsp all-purpose flour',
          'Pinch of salt',
        ],
        steps: [
          'Beat butter until light and fluffy, about 2 minutes.',
          'Add powdered sugar and beat until combined.',
          'Add eggs one at a time, beating well after each addition.',
          'Mix in vanilla extract.',
          'Fold in almond flour, all-purpose flour, and salt until just combined.',
          'Do not overmix. Refrigerate until ready to use.',
        ],
      },
      {
        heading: 'Assembly',
        ingredients: [
          '4 day-old croissants (day-old is key — they hold up better)',
          '½ cup sliced almonds',
          'Powdered sugar for dusting',
        ],
        steps: [
          'Preheat oven to 350°F (175°C). Line a baking sheet with parchment.',
          'Slice each croissant in half horizontally (like a sandwich bun).',
          'Generously brush the cut sides and exterior of each croissant with simple syrup. Be generous — the syrup is what makes them moist and flavorful.',
          'Spread a generous layer of almond cream on the bottom half of each croissant.',
          'Replace the top half. Spread more almond cream on the top exterior.',
          'Press sliced almonds generously onto the almond cream on top.',
          'Place on prepared baking sheet and bake for 20–25 minutes until the almond cream is set and the almonds are golden brown.',
          'Let cool for 10 minutes, then dust generously with powdered sugar.',
          'Serve warm. Try not to eat all four yourself.',
        ],
        tip: 'The simple syrup is non-negotiable. It re-hydrates the croissant and adds flavor. Day-old croissants are actually better here than fresh ones — they absorb the syrup without falling apart.',
      },
    ],
    notes: [
      'Store leftovers at room temperature for up to 1 day, or refrigerate for up to 3 days. Re-warm in a 325°F oven for 8–10 minutes.',
      'You can make the almond cream up to 3 days in advance and refrigerate it.',
      'Add a tablespoon of dark rum to the simple syrup for a more traditional French flavor.',
      'If your croissants are very fresh, leave them out uncovered overnight to dry out slightly before using.',
    ],
  },
  {
    slug: 'strawberry-shortcake',
    title: 'Fluffy Strawberry Shortcake with Chiffon Cake',
    category: 'Cakes',
    image: RECIPE_IMAGES.strawberryShortcake,
    prepTime: '30 min',
    cookTime: '30–35 min',
    yield: 'Serves 8–10',
    intro: `Happy Valentine's Day (or any day you want to feel celebrated)! This strawberry shortcake is built on a Japanese-style chiffon cake — impossibly light, with a cloud-like crumb — layered with stabilized whipped cream and fresh strawberries. Unlike a traditional American shortcake, this version is delicate, elegant, and just sweet enough. The secret to the fluffiest chiffon? Properly whipped egg whites, folded in gently. And the secret to whipped cream that holds for hours? A little cream cheese.`,
    sections: [
      {
        heading: 'Chiffon Cake',
        ingredients: [
          '6 large eggs, separated, room temperature',
          '200g (1 cup) granulated sugar, divided',
          '120ml (½ cup) vegetable oil',
          '120ml (½ cup) whole milk',
          '1 tsp vanilla extract',
          '180g (1½ cups) cake flour',
          '2 tsp baking powder',
          '¼ tsp salt',
          '¼ tsp cream of tartar',
        ],
        steps: [
          'Preheat oven to 325°F (165°C). Do NOT grease your cake pans — the batter needs to cling to the sides to rise properly.',
          'In a large bowl, whisk egg yolks with 100g of the sugar until pale and thick.',
          'Whisk in oil, milk, and vanilla until smooth.',
          'Sift in cake flour, baking powder, and salt. Fold until just combined.',
          'In a separate clean bowl, beat egg whites with cream of tartar until foamy.',
          'Gradually add remaining 100g sugar and beat to stiff, glossy peaks. The whites should hold a straight peak when you lift the beater.',
          'Gently fold ⅓ of the meringue into the yolk batter to lighten it.',
          'Fold in remaining meringue in two additions. Be gentle — deflating the whites will give you a dense cake.',
          'Pour into two ungreased 8-inch round pans. Bake for 30–35 minutes until a skewer comes out clean.',
          'Invert pans immediately and let cool completely upside down (this prevents the cake from sinking).',
        ],
        tip: 'Make sure your bowl and beaters are completely clean and grease-free before whipping egg whites. Even a drop of yolk will prevent them from whipping properly.',
      },
      {
        heading: 'Stabilized Whipped Cream',
        ingredients: [
          '480ml (2 cups) heavy whipping cream, cold',
          '60g (2 oz) full-fat cream cheese, room temperature',
          '60g (½ cup) powdered sugar, sifted',
          '1 tsp vanilla extract',
        ],
        steps: [
          'Beat cream cheese until completely smooth with no lumps.',
          'Add powdered sugar and vanilla and beat until combined.',
          'With mixer running, slowly pour in cold heavy cream.',
          'Increase speed and beat to stiff peaks.',
          'The cream cheese acts as a stabilizer — this whipped cream will hold its shape for 24+ hours without weeping.',
        ],
        tip: 'The cream cheese trick is a game-changer. You cannot taste it in the final product — it just keeps your whipped cream from turning into a sad puddle.',
      },
      {
        heading: 'Assembly',
        ingredients: [
          '500g (about 1 lb) fresh strawberries, hulled and sliced',
          '2 tbsp sugar',
          'Whole strawberries for decoration',
        ],
        steps: [
          'Toss sliced strawberries with 2 tbsp sugar. Let macerate for 15–20 minutes until juicy.',
          'Once cakes are completely cool, use a serrated knife to level the tops if needed.',
          'Place first cake layer on your serving plate. Spread a generous layer of whipped cream.',
          'Arrange macerated strawberries over the cream, pressing in slightly.',
          'Place second cake layer on top.',
          'Frost the top and sides with remaining whipped cream.',
          'Decorate with fresh whole strawberries.',
          'Refrigerate for at least 1 hour before slicing for cleanest results.',
        ],
      },
    ],
    notes: [
      'This cake is best eaten the day it's assembled. Store refrigerated for up to 2 days.',
      'You can bake the chiffon layers up to 1 day ahead and wrap tightly at room temperature.',
      'For a more elegant finish, pipe the whipped cream using a star tip.',
      'Add a thin layer of strawberry jam between layers for extra berry flavor.',
    ],
  },
  {
    slug: 'macarons',
    title: 'How to Make Macarons (French Meringue Method)',
    category: 'Pastries',
    image: RECIPE_IMAGES.macarons,
    prepTime: '45 min + 30–60 min resting',
    cookTime: '12–15 min',
    yield: 'Makes ~24 shells (12 sandwich cookies)',
    intro: `Let me say something controversial: the internet is obsessed with perfect macarons to a degree that I think actively discourages people from making them. Yes, macarons are finicky. Yes, hollow shells happen. Yes, the feet might not always be perfect. But you know what? They will still taste absolutely delicious. I went to French pastry school. I've made hundreds of batches. And I still get imperfect shells sometimes. That's baking. This recipe uses the French meringue method — no cooked sugar, no thermometer required. It's the most approachable method for home bakers, and it produces beautiful results when you follow the steps carefully.`,
    sections: [
      {
        heading: 'Tant Pour Tant (TPT — Almond Base)',
        ingredients: [
          '150g almond flour',
          '150g powdered sugar',
          'Gel food coloring (optional)',
        ],
        steps: [
          'Sift almond flour and powdered sugar together through a fine mesh sieve.',
          'Discard any large pieces that won't pass through.',
          'For extra-smooth shells, pulse the mixture in a food processor before sifting.',
          'Set aside.',
        ],
        tip: 'Do not skip sifting. Large chunks of almond will create lumpy shells. If your almond flour is coarse, process it in a food processor first.',
      },
      {
        heading: 'The Meringue',
        ingredients: [
          '110g egg whites (aged 24–48 hours in the fridge, uncovered — or fresh works too)',
          '95g granulated sugar',
          '¼ tsp cream of tartar',
        ],
        steps: [
          'Make sure your bowl and whisk are impeccably clean. Any grease will prevent the whites from whipping.',
          'Start whipping egg whites on medium speed until foamy.',
          'Add cream of tartar.',
          'Gradually add sugar in a slow, steady stream while continuing to whip.',
          'Increase speed to medium-high. Whip until you reach stiff, glossy peaks.',
          'The meringue should be thick, shiny, and hold a straight stiff peak.',
          'Add gel food coloring now if using, and whip briefly to incorporate.',
        ],
        tip: 'Aged egg whites have less moisture, which can result in crisper shells. But honestly, fresh whites work fine. Don't stress about it.',
      },
      {
        heading: 'The Macaronnage (Folding)',
        ingredients: [],
        steps: [
          'Add the TPT mixture to the meringue all at once.',
          'Using a flexible spatula, fold and press the batter against the sides of the bowl.',
          'The goal is to deflate the meringue slightly and create a smooth, flowing batter.',
          'Test consistency: lift your spatula and let batter fall. It should flow like lava and the ribbon should disappear back into the batter within 10–15 seconds.',
          'This is called the "lava test" or "ribbon test." Underfolded batter will give you lumpy shells. Overfolded batter will spread too much and give you flat, footless shells.',
          'Transfer to a piping bag fitted with a round tip (Wilton 1A or similar).',
          'Pipe 1.5-inch rounds onto parchment-lined baking sheets. Hold the bag perpendicular to the tray and release pressure before lifting.',
          'Bang the tray firmly on the counter 3–4 times to release air bubbles.',
          'Pop any remaining bubbles with a toothpick.',
          'Let shells rest at room temperature for 30–60 minutes until they form a dry skin. They should not stick when you lightly touch them.',
          'Preheat oven to 300°F (150°C).',
          'Bake for 12–15 minutes. Shells are done when they don't wiggle when gently pushed.',
          'Let cool completely on the tray before removing.',
        ],
        tip: 'Hollow shells are one of the most common macaron problems. They're usually caused by under-whipped meringue, oven temperature too high, or shells not resting long enough. If you get hollow shells — they still taste great. Eat them anyway and try again.',
        note: 'A word on "perfect" macarons: the internet will have you believe that anything less than perfectly domed, evenly footed, non-hollow macarons is a failure. I disagree. Macarons are a technique-driven pastry with a learning curve. Every batch teaches you something. Imperfect macarons eaten fresh from the oven are still one of life's great pleasures.',
      },
    ],
    notes: [
      'Fill with buttercream, ganache, jam, or any filling you like. Let filled macarons "mature" in the fridge for 24 hours — the shells soften and the flavor deepens.',
      'Unfilled shells can be stored at room temperature in an airtight container for up to 3 days, or frozen for 1 month.',
      'Humidity is the enemy of macarons. Avoid making them on rainy or very humid days.',
      'Every oven is different. Get to know your oven and adjust temperature/time accordingly.',
      'Save your leftover egg yolks! Use them for crème brûlée, pastry cream, or lemon curd.',
    ],
  },
  {
    slug: 'pumpkin-cookies',
    title: 'Chewy Pumpkin Spice Choc Chip Cookies',
    category: 'Cookies',
    image: RECIPE_IMAGES.pumpkinCookie,
    prepTime: '20 min + 1 hr chilling',
    cookTime: '13–15 min',
    yield: 'Makes ~10 large cookies',
    intro: `Pumpkin cookies have a bad reputation for being cakey and soft in a sad way — almost muffin-top-like. These are not those cookies. These are chewy, deeply flavored, packed with warm spice, and studded with chocolate chips. The secret to chewiness in a pumpkin cookie is removing moisture. Pumpkin puree is about 90% water, and that water is what makes most pumpkin cookies turn into little soft pucks. My solution: brown butter (which removes water), an egg yolk only (no white — whites add moisture), and molasses instead of brown sugar (more flavor, less water activity).`,
    sections: [
      {
        heading: 'The Cookies',
        ingredients: [
          '115g (1 stick) unsalted butter',
          '100g (½ cup) granulated sugar',
          '50g (about 2 tbsp) molasses (NOT blackstrap — use regular or mild molasses)',
          '1 large egg yolk, room temperature',
          '120g (½ cup) pumpkin puree (canned is perfect)',
          '1 tsp vanilla extract',
          '190g (1½ cups) all-purpose flour',
          '1 tsp baking soda',
          '½ tsp salt',
          '1½ tsp cinnamon',
          '½ tsp ginger',
          '¼ tsp nutmeg',
          '¼ tsp cloves',
          '170g (1 cup) chocolate chips',
        ],
        steps: [
          'Brown the butter: melt butter in a light-colored saucepan over medium heat, swirling frequently. Continue cooking until the butter turns golden and smells nutty. Watch carefully — it goes from brown to burnt quickly. Pour into a large bowl and let cool for 10 minutes.',
          'Add granulated sugar and molasses to the browned butter. Whisk until combined.',
          'Add egg yolk and vanilla. Whisk vigorously for about 1 minute.',
          'Add pumpkin puree and whisk until smooth.',
          'Sift in flour, baking soda, salt, and spices. Fold until just combined.',
          'Fold in chocolate chips.',
          'Cover dough and refrigerate for at least 1 hour (up to 48 hours — longer = more flavor).',
          'Preheat oven to 375°F (190°C). Line baking sheets with parchment.',
          'Scoop dough into balls (~50g each for large cookies). Place on prepared baking sheets, spacing 3 inches apart.',
          'Bake for 13–15 minutes until edges are set but centers still look slightly underdone.',
          'Remove from oven and immediately use a round cookie cutter or glass to "scoot" the cookies into perfect circles while hot.',
          'Let cool on the tray for 5 minutes before transferring. They will firm up as they cool.',
        ],
        tip: 'I use molasses instead of brown sugar because it has a more concentrated, complex flavor and different moisture behavior. Brown sugar is just granulated sugar + molasses — so by using them separately, I can control the ratio. Also: the egg yolk-only approach is crucial. The white of an egg adds moisture and lift (great for cakes, not for chewy cookies). Yolk-only = richness and chew.',
        note: 'If you have leftover egg whites from this recipe, save them for macarons! You can refrigerate uncovered for up to 48 hours or freeze in an airtight container.',
      },
    ],
    notes: [
      'Store cookies in an airtight container at room temperature for up to 4 days.',
      'Cookie dough balls can be frozen for up to 2 months. Bake from frozen, adding 2–3 minutes to the bake time.',
      'Don't skip chilling. The rest time hydrates the flour and deepens the spice flavor.',
      'Add a sprinkle of flaky sea salt on top before baking for a beautiful sweet-salty finish.',
    ],
  },
  {
    slug: 'lemon-curd',
    title: 'Quick and Easy Microwave Lemon Curd',
    category: 'Basics',
    image: RECIPE_IMAGES.lemonCurd,
    prepTime: '5 min',
    cookTime: '5–6 min',
    yield: 'Makes ~1.5 cups',
    intro: `I discovered microwave lemon curd by accident during my college years, when I needed lemon curd for a tart and had no desire to stand over a double boiler stirring for 20 minutes. The result? Honestly identical to the stovetop version — glossy, intensely lemony, perfectly thickened, and done in under 10 minutes total. The microwave method works because you cook in short bursts and whisk between each round, which prevents the eggs from scrambling. It's genuinely foolproof once you understand the rhythm. I've never gone back to the stovetop.`,
    sections: [
      {
        heading: 'Microwave Lemon Curd',
        ingredients: [
          '3 large eggs',
          '200g (1 cup) granulated sugar',
          '120ml (½ cup) fresh lemon juice (about 3–4 lemons)',
          '1 tbsp lemon zest',
          '115g (1 stick / ½ cup) unsalted butter, cubed',
          'Pinch of salt',
        ],
        steps: [
          'In a large microwave-safe bowl, whisk together eggs and sugar until smooth.',
          'Add lemon juice, lemon zest, and salt. Whisk to combine.',
          'Add butter cubes.',
          'Microwave on HIGH for 1 minute. Remove and whisk thoroughly.',
          'Microwave for another 1 minute. Remove and whisk thoroughly.',
          'Continue in 30-second intervals, whisking after each, until the curd thickens and coats the back of a spoon. This usually takes 5–6 minutes total.',
          'The curd is ready when it reaches about 170°F (77°C) and a line drawn through the curd on the back of a spoon holds its shape.',
          'Strain through a fine mesh sieve into a clean jar or container to remove any bits of zest or cooked egg.',
          'Press plastic wrap directly onto the surface of the curd to prevent a skin from forming.',
          'Refrigerate until cold and set, at least 2 hours. The curd will thicken further as it cools.',
        ],
        tip: 'The key is short bursts with thorough whisking in between. If you go too long between whisks, the edges of the bowl will overcook and you'll get scrambled egg bits. The sieving step at the end is your safety net — even if you get a little cooked egg, straining will catch it.',
      },
    ],
    notes: [
      'Keeps refrigerated in an airtight jar for up to 2 weeks.',
      'Use on toast, scones, tarts, as a cake filling, swirled into whipped cream, or eaten by the spoonful.',
      'For a more intense flavor, add a bit of lemon oil in addition to the zest.',
      'You can make lime curd, orange curd, or passion fruit curd using the exact same method — just swap the citrus.',
      'For a richer curd, add an extra egg yolk.',
    ],
  },
];
